"""
config.py
---------
Constantes globais, configuração do banco e lista de compostos.
Importado por todos os outros módulos.
"""

import logging
import sys
from datetime import datetime
from pathlib import Path

# ============================================================
# Logging — console + arquivo com timestamp
# ============================================================

def _setup_logging() -> Path:
    """
    Configura o root logger com dois handlers:
      - StreamHandler  → console (stdout)
      - FileHandler    → logs/populate_YYYY-MM-DD_HHhMM.log

    Retorna o caminho do arquivo de log criado.
    Idempotente: não adiciona handlers duplicados se chamado mais de uma vez.
    """
    LOG_DIR = Path(__file__).parent / "logs"
    LOG_DIR.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%Hh%M")
    log_file  = LOG_DIR / f"populate_{timestamp}.log"

    fmt     = "%(asctime)s [%(levelname)s] %(name)s — %(message)s"
    datefmt = "%H:%M:%S"
    formatter = logging.Formatter(fmt, datefmt=datefmt)

    root = logging.getLogger()
    if root.handlers:          # já configurado — não duplicar
        return log_file

    root.setLevel(logging.INFO)

    # Console
    console = logging.StreamHandler(sys.stdout)
    console.setFormatter(formatter)
    root.addHandler(console)

    # Arquivo
    file_handler = logging.FileHandler(log_file, encoding="utf-8")
    file_handler.setFormatter(formatter)
    root.addHandler(file_handler)

    return log_file


_log_file = _setup_logging()

# Disponível para outros módulos que queiram exibir o caminho do log
LOG_FILE: Path = _log_file

# ============================================================
# Banco de dados
# ============================================================
#
# Configuração resolvida nesta ordem de prioridade:
#
#   1. DATABASE_URL  (Supabase, Railway, Render, Heroku...)
#        postgresql://user:pass@host:5432/dbname
#        postgresql://user:pass@host:5432/dbname?sslmode=require
#
#   2. Variáveis individuais (qualquer banco)
#        DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD, DB_SSLMODE
#
#   3. Defaults para o Docker local
#        localhost:5432 / chembl_pubmed / admin / admin123
#
# Exemplos de uso:
#
#   # Docker local (sem variáveis — usa defaults)
#   python populate.py
#
#   # Supabase
#   $env:DATABASE_URL="postgresql://postgres.xxx:senha@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"
#   python populate.py
#
#   # Outra instância PostgreSQL
#   $env:DB_HOST="meu-servidor.com"; $env:DB_PASSWORD="senha"
#   python populate.py

import os
from urllib.parse import urlparse

def _resolve_db_config() -> dict:
    """
    Resolve a configuração do banco a partir de variáveis de ambiente.
    Retorna um dict compatível com psycopg2.connect(**config).
    """
    database_url = os.environ.get("DATABASE_URL", "").strip()

    if database_url:
        # ── Modo 1: DATABASE_URL ─────────────────────────────
        # Supabase e maioria dos PaaS usam este formato.
        parsed = urlparse(database_url)
        config = {
            "host":     parsed.hostname,
            "port":     parsed.port or 5432,
            "dbname":   parsed.path.lstrip("/"),
            "user":     parsed.username,
            "password": parsed.password,
        }
        # Parâmetros extras da query string (ex: sslmode=require)
        if parsed.query:
            for param in parsed.query.split("&"):
                if "=" in param:
                    k, v = param.split("=", 1)
                    config[k] = v

        # Supabase exige SSL — garantir mesmo que não esteja na URL
        if "supabase" in (parsed.hostname or ""):
            config.setdefault("sslmode", "require")

        return config

    # ── Modo 2: variáveis individuais + defaults locais ──────
    return {
        "host":     os.environ.get("DB_HOST",     "localhost"),
        "port":     int(os.environ.get("DB_PORT", "5432")),
        "dbname":   os.environ.get("DB_NAME",     "chembl_pubmed"),
        "user":     os.environ.get("DB_USER",     "admin"),
        "password": os.environ.get("DB_PASSWORD", "admin123"),
        **({} if not os.environ.get("DB_SSLMODE")
           else {"sslmode": os.environ["DB_SSLMODE"]}),
    }


DB_CONFIG: dict = _resolve_db_config()

# ============================================================
# APIs
# ============================================================

CHEMBL_BASE  = "https://www.ebi.ac.uk/chembl/api/data"
PUBMED_BASE  = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"

# ============================================================
# Limites por composto
# ============================================================

MAX_BIOACT   = 5   # bioatividades buscadas no ChEMBL
MAX_ARTICLES = 5   # artigos buscados no PubMed

# ============================================================
# Compostos populares
# Formato: (chembl_id, nome_comum)
# IDs verificados diretamente no ChEMBL (max_phase=4)
# ============================================================

POPULAR_COMPOUNDS = [
    # ── Analgésicos / Anti-inflamatórios ──────────────────────
    ("CHEMBL25",       "Aspirin"),          # NSAID / antiagregante plaquetário
    ("CHEMBL521",      "Ibuprofen"),        # NSAID
    ("CHEMBL112",      "Paracetamol"),      # analgésico / antitérmico
    ("CHEMBL154",      "Naproxen"),         # NSAID
    ("CHEMBL599",      "Meloxicam"),        # NSAID inibidor preferencial de COX-2
    ("CHEMBL1237044",  "Tramadol"),         # opioide atípico / inibidor de recaptação

    # ── Sistema Nervoso Central ────────────────────────────────
    ("CHEMBL113",      "Caffeine"),         # estimulante (inibidor de adenosina)
    ("CHEMBL12",       "Diazepam"),         # benzodiazepínico
    ("CHEMBL661",      "Alprazolam"),       # benzodiazepínico (ansiolítico)
    ("CHEMBL70",       "Morphine"),         # opioide
    ("CHEMBL41",       "Fluoxetine"),       # antidepressivo SSRI
    ("CHEMBL809",      "Sertraline"),       # antidepressivo SSRI
    ("CHEMBL1009",     "Levodopa"),         # precursor de dopamina (Parkinson)
    ("CHEMBL502",      "Donepezil"),        # inibidor de acetilcolinesterase (Alzheimer)
    ("CHEMBL940",      "Gabapentin"),       # anticonvulsivante / gabaminético
    ("CHEMBL1059",     "Pregabalin"),       # anticonvulsivante / gabaminético
    ("CHEMBL54",       "Haloperidol"),      # antipsicótico típico (bloq. D2)
    ("CHEMBL716",      "Quetiapine"),       # antipsicótico atípico
    ("CHEMBL911",      "Zolpidem"),         # hipnótico não-benzodiazepínico
    ("CHEMBL1200826",  "Lithium carbonate"),# estabilizador de humor (transt. bipolar)

    # ── Cardiovascular ────────────────────────────────────────
    ("CHEMBL1464",     "Warfarin"),         # anticoagulante
    ("CHEMBL1491",     "Amlodipine"),       # bloqueador de canal de cálcio
    ("CHEMBL193",      "Nifedipine"),       # bloqueador de canal de cálcio (DHP)
    ("CHEMBL1237",     "Lisinopril"),       # inibidor da ECA
    ("CHEMBL578",      "Enalapril"),        # inibidor da ECA (pró-fármaco)
    ("CHEMBL191",      "Losartan"),         # antagonista receptor angiotensina II
    ("CHEMBL1069",     "Valsartan"),        # antagonista receptor angiotensina II
    ("CHEMBL1064",     "Simvastatin"),      # estatina (HMG-CoA reductase)
    ("CHEMBL1487",     "Atorvastatin"),     # estatina (HMG-CoA reductase)
    ("CHEMBL192",      "Sildenafil"),       # inibidor PDE5
    ("CHEMBL27",       "Propranolol"),      # beta-bloqueador não seletivo
    ("CHEMBL1751",     "Digoxin"),          # glicosídeo cardíaco (inib. Na/K-ATPase)

    # ── Metabólico / Endócrino ────────────────────────────────
    ("CHEMBL1431",     "Metformin"),        # antidiabético (biguanida)
    ("CHEMBL384467",   "Dexamethasone"),    # corticosteroide
    ("CHEMBL1422",     "Sitagliptin"),      # inibidor de DPP-4
    ("CHEMBL2107830",  "Empagliflozin"),    # inibidor SGLT-2

    # ── Gastrointestinal ──────────────────────────────────────
    ("CHEMBL1503",     "Omeprazole"),       # inibidor de bomba de prótons
    ("CHEMBL1502",     "Pantoprazole"),     # inibidor de bomba de prótons

    # ── Antimicrobianos ───────────────────────────────────────
    ("CHEMBL1082",     "Amoxicillin"),      # antibiótico betalactâmico
    ("CHEMBL8",        "Ciprofloxacin"),    # antibiótico fluoroquinolona
    ("CHEMBL1433",     "Doxycycline"),      # antibiótico tetraciclínico
    ("CHEMBL262777",   "Vancomycin"),       # glicopeptídeo (infecções por MRSA)

    # ── Antivirais ────────────────────────────────────────────
    ("CHEMBL1229",     "Oseltamivir"),      # antiviral (inibidor de neuraminidase)
    ("CHEMBL1486",     "Tenofovir"),        # antirretroviral (inibidor de TN-RT)
    ("CHEMBL223228",   "Efavirenz"),        # antirretroviral (inibidor não-nucleosídeo de RT)

    # ── Oncologia ─────────────────────────────────────────────
    ("CHEMBL83",       "Tamoxifen"),        # antagonista receptor de estrogênio
    ("CHEMBL941",      "Imatinib"),         # inibidor de tirosina quinase (BCR-ABL)
    ("CHEMBL34259",    "Methotrexate"),     # antimetabólito (inibidor de DHFR)
    ("CHEMBL1773",     "Capecitabine"),     # pró-fármaco do 5-fluorouracil
    ("CHEMBL1351",     "Carboplatin"),      # agente alquilante (derivado de platina)

    # ── Respiratório ──────────────────────────────────────────
    ("CHEMBL1900528",  "Tiotropium"),       # anticolinérgico de longa ação (DPOC)
    ("CHEMBL1473",     "Fluticasone"),      # corticosteroide inalatório

    ("CHEMBL2", "PRAZOSIN"),
    ("CHEMBL3", "NICOTINE"),
    ("CHEMBL4", "OFLOXACIN"),
    ("CHEMBL5", "NALIDIXIC ACID"),
    ("CHEMBL6", "INDOMETHACIN"),
    ("CHEMBL8", "CIPROFLOXACIN"),
    ("CHEMBL9", "NORFLOXACIN"),
    ("CHEMBL10", "SB-203580"),
    ("CHEMBL11", "IMIPRAMINE"),
    ("CHEMBL12", "DIAZEPAM"),
    ("CHEMBL13", "METOPROLOL"),
    ("CHEMBL14", "CARBACHOL"),
    ("CHEMBL16", "PHENYTOIN"),
    ("CHEMBL17", "DICHLORPHENAMIDE"),
    ("CHEMBL18", "ETHOXZOLAMIDE"),
    ("CHEMBL19", "METHAZOLAMIDE"),
    ("CHEMBL20", "ACETAZOLAMIDE"),
    ("CHEMBL21", "SULFANILAMIDE"),
    ("CHEMBL22", "TRIMETHOPRIM"),
    ("CHEMBL23", "DILTIAZEM"),
    ("CHEMBL24", "ATENOLOL"),
    ("CHEMBL25", "ASPIRIN"),
    ("CHEMBL26", "SULPIRIDE"),
    ("CHEMBL27", "PROPRANOLOL"),
    ("CHEMBL28", "APIGENIN"),
    ("CHEMBL29", "PENICILLIN G"),
    ("CHEMBL30", "CIMETIDINE"),
    ("CHEMBL31", "GATIFLOXACIN"),
    ("CHEMBL32", "MOXIFLOXACIN"),
    ("CHEMBL33", "LEVOFLOXACIN ANHYDROUS"),
    ("CHEMBL35", "FUROSEMIDE"),
    ("CHEMBL36", "PYRIMETHAMINE"),
    ("CHEMBL38", "TRETINOIN"),
    ("CHEMBL39", "SEROTONIN"),
    ("CHEMBL40", "PHENOBARBITAL"),
    ("CHEMBL41", "FLUOXETINE"),
    ("CHEMBL42", "CLOZAPINE"),
    ("CHEMBL43", "AMSACRINE"),
    ("CHEMBL44", "GENISTEIN"),
    ("CHEMBL45", "MELATONIN"),
    ("CHEMBL46", "ONDANSETRON"),
    ("CHEMBL47", "ALPHA-TOCOPHEROL"),
    ("CHEMBL49", "BUSPIRONE"),
    ("CHEMBL50", "QUERCETIN"),
    ("CHEMBL51", "KETANSERIN"),
    ("CHEMBL52", "NORDIHYDROGUAIARETIC ACID"),
    ("CHEMBL53", "APOMORPHINE"),
    ("CHEMBL54", "HALOPERIDOL"),
    ("CHEMBL55", "PENTAMIDINE"),
    ("CHEMBL56", "8-OH-DPAT"),
    ("CHEMBL57", "NEVIRAPINE"),
    ("CHEMBL58", "MITOXANTRONE"),
    ("CHEMBL59", "DOPAMINE"),
    ("CHEMBL61", "PODOFILOX"),
    ("CHEMBL62", "SCH-23390"),
    ("CHEMBL63", "ROLIPRAM"),
    ("CHEMBL64", "ISONIAZID"),
    ("CHEMBL65", "CAMPTOTHECIN"),
    ("CHEMBL66", "(+)-TAXIFOLIN"),
    ("CHEMBL67", "COMBRETASTATIN A4"),
    ("CHEMBL70", "MORPHINE"),
    ("CHEMBL71", "CHLORPROMAZINE"),
    ("CHEMBL72", "DESIPRAMINE"),
    ("CHEMBL74", "CROMOLYN SODIUM"),
    ("CHEMBL76", "CHLOROQUINE"),
    ("CHEMBL77", "ARTEMISIN"),
    ("CHEMBL79", "LIDOCAINE"),
    ("CHEMBL80", "NALOXONE"),
    ("CHEMBL81", "RALOXIFENE"),
    ("CHEMBL83", "TAMOXIFEN"),
    ("CHEMBL84", "TOPOTECAN"),
    ("CHEMBL85", "RISPERIDONE"),
    ("CHEMBL86", "METOCLOPRAMIDE"),
    ("CHEMBL88", "CYCLOPHOSPHAMIDE ANHYDROUS"),
    ("CHEMBL90", "HISTAMINE"),
    ("CHEMBL91", "MICONAZOLE"),
    ("CHEMBL92", "DOCETAXEL ANHYDROUS"),
    ("CHEMBL93", "ZILEUTON"),
    ("CHEMBL94", "PHYSOSTIGMINE"),
    ("CHEMBL95", "TACRINE"),
    ("CHEMBL96", "GAMMA-AMINOBUTYRIC ACID"),
    ("CHEMBL98", "VORINOSTAT"),
    ("CHEMBL99", "TRICHOSTATIN"),
    ("CHEMBL100", "LEVCROMAKALIM"),
    ("CHEMBL101", "PHENYLBUTAZONE"),
    ("CHEMBL103", "PROGESTERONE"),
    ("CHEMBL104", "CLOTRIMAZOLE"),
    ("CHEMBL105", "MITOMYCIN"),
    ("CHEMBL106", "FLUCONAZOLE"),
    ("CHEMBL107", "COLCHICINE"),
    ("CHEMBL108", "CARBAMAZEPINE"),
    ("CHEMBL109", "VALPROIC ACID"),
    ("CHEMBL110", "BENZNIDAZOLE"),
    ("CHEMBL111", "RIMONABANT"),
    ("CHEMBL112", "ACETAMINOPHEN"),
    ("CHEMBL113", "CAFFEINE"),
    ("CHEMBL114", "SAQUINAVIR"),
    ("CHEMBL115", "INDINAVIR ANHYDROUS"),
    ("CHEMBL116", "AMPRENAVIR"),
    ("CHEMBL117", "CHRYSIN"),
    ("CHEMBL118", "CELECOXIB"),
    ("CHEMBL119", "TRIMETREXATE"),
    ("CHEMBL121", "ROSIGLITAZONE"),
    ("CHEMBL122", "ROFECOXIB"),
    ("CHEMBL123", "ELLIPTECINE"),
    ("CHEMBL125", "MILTEFOSINE"),
    ("CHEMBL126", "LINEZOLID"),
    ("CHEMBL127", "MEROPENEM"),
    ("CHEMBL128", "SUMATRIPTAN"),
    ("CHEMBL129", "ZIDOVUDINE"),
    ("CHEMBL130", "CHLORAMPHENICOL"),
    ("CHEMBL131", "PREDNISOLONE"),
    ("CHEMBL134", "CLONIDINE"),
    ("CHEMBL135", "ESTRADIOL"),
    ("CHEMBL137", "METRONIDAZOLE"),
    ("CHEMBL139", "DICLOFENAC"),
    ("CHEMBL140", "CURCUMIN"),
    ("CHEMBL141", "LAMIVUDINE"),
    ("CHEMBL145", "CAFFEIC ACID"),
    ("CHEMBL146", "BUTYLATED HYDROXYTOLUENE"),
    ("CHEMBL148", "IMIPENEM ANHYDROUS"),
    ("CHEMBL150", "KAEMPFEROL"),
    ("CHEMBL151", "LUTEOLIN"),
    ("CHEMBL152", "CIDOFOVIR ANHYDROUS"),
    ("CHEMBL153", "TROLOX"),
    ("CHEMBL154", "NAPROXEN"),
    ("CHEMBL158", "AZTREONAM"),
    ("CHEMBL159", "VINBLASTINE"),
    ("CHEMBL160", "CYCLOSPORINE"),
    ("CHEMBL161", "CEFTRIAXONE"),
    ("CHEMBL163", "RITONAVIR"),
    ("CHEMBL164", "MYRICETIN"),
    ("CHEMBL165", "RESVERATROL"),
    ("CHEMBL166", "MELARSOPROL"),
    ("CHEMBL168", "OLEANOLIC_ACID"),
    ("CHEMBL169", "URSOLIC ACID"),
    ("CHEMBL170", "QUININE"),
    ("CHEMBL172", "(S,R)-MEFLOQUINE"),
    ("CHEMBL174", "AMPICILLIN"),
    ("CHEMBL175", "DEXIBUPROFEN"),
    ("CHEMBL176", "BEKANAMYCIN"),
    ("CHEMBL177", "AMIKACIN"),
    ("CHEMBL178", "DAUNORUBICIN"),
    ("CHEMBL181", "DIAZOXIDE"),
    ("CHEMBL182", "GANCICLOVIR"),
    ("CHEMBL183", "1,3-DIPROPYL-8-CYCLOPENTYLXANTHINE [DPCPX]"),
    ("CHEMBL184", "ACYCLOVIR"),
    ("CHEMBL185", "FLUOROURACIL"),
    ("CHEMBL186", "CEFEPIME"),
    ("CHEMBL188", "WIN-552122"),
    ("CHEMBL189", "MILRINONE"),
    ("CHEMBL190", "THEOPHYLLINE ANHYDROUS"),
    ("CHEMBL191", "LOSARTAN"),
    ("CHEMBL192", "SILDENAFIL"),
    ("CHEMBL193", "NIFEDIPINE"),
    ("CHEMBL196", "ASCORBIC ACID"),
    ("CHEMBL197", "DEXVERAPAMIL"),
    ("CHEMBL403", "SULBACTAM"),
    ("CHEMBL404", "TAZOBACTAM"),
    ("CHEMBL405", "AMPHETAMINE"),
    ("CHEMBL406", "INDAPAMIDE"),
    ("CHEMBL407", "FLUMAZENIL"),
    ("CHEMBL408", "TROGLITAZONE"),
    ("CHEMBL409", "BICALUTAMIDE"),
    ("CHEMBL411", "DIETHYLSTILBESTROL"),
    ("CHEMBL413", "SIROLIMUS"),
    ("CHEMBL414", "CARZENIDE"),
    ("CHEMBL415", "CLOMIPRAMINE"),
    ("CHEMBL416", "METHOXSALEN"),
    ("CHEMBL417", "EPIRUBICIN"),
    ("CHEMBL418", "2,4-DISULFAMYLTRIFLUOROMETHYLANILINE"),
    ("CHEMBL419", "MAFENIDE"),
    ("CHEMBL420", "GUANABENZ"),
    ("CHEMBL421", "SULFASALAZINE"),
    ("CHEMBL422", "TRIFLUOPERAZINE"),
    ("CHEMBL423", "BETAXOLOL"),
    ("CHEMBL424", "SALICYLIC ACID"),
    ("CHEMBL425", "OLSALAZINE"),
    ("CHEMBL427", "MECHLORETHAMINE"),
    ("CHEMBL428", "TROVAFLOXACIN"),
    ("CHEMBL429", "LABETALOL"),
    ("CHEMBL430", "GEMIFLOXACIN"),
    ("CHEMBL431", "SPIRAPRIL"),
    ("CHEMBL433", "VALPROATE SODIUM"),
    ("CHEMBL434", "ISOPROTERENOL"),
    ("CHEMBL435", "HYDROCHLOROTHIAZIDE"),
    ("CHEMBL436", "TOLRESTAT"),
    ("CHEMBL437", "SULFATHIAZOLE"),
    ("CHEMBL438", "SULFAMERAZINE"),
    ("CHEMBL439", "SULFADIAZINE"),
    ("CHEMBL440", "THIAMYLAL"),
    ("CHEMBL441", "THIOPENTAL"),
    ("CHEMBL442", "ERGOTAMINE"),
    ("CHEMBL443", "SULFAMETHOXAZOLE"),
    ("CHEMBL444", "BARBITAL"),
    ("CHEMBL445", "NORTRIPTYLINE"),
    ("CHEMBL446", "SULFAMETHAZINE"),
    ("CHEMBL447", "SECOBARBITAL"),
    ("CHEMBL448", "PENTOBARBITAL"),
    ("CHEMBL449", "BUTABARBITAL"),
    ("CHEMBL450", "METHARBITAL"),
    ("CHEMBL451", "CHLORDIAZEPOXIDE"),
    ("CHEMBL452", "CLONAZEPAM"),
    ("CHEMBL453", "SULFISOXAZOLE"),
    ("CHEMBL454", "BUTALBITAL"),
    ("CHEMBL455", "SULFACETAMIDE"),
    ("CHEMBL456", "ETHACRYNIC ACID"),
    ("CHEMBL457", "GEMFIBROZIL"),
    ("CHEMBL459", "METHYLDOPA"),
    ("CHEMBL460", "MOLINDONE"),
    ("CHEMBL461", "HIPPURIC ACID"),
    ("CHEMBL462", "4-CHLOROHIPPURIC ACID"),
    ("CHEMBL463", "AMINOHIPPURIC ACID"),
    ("CHEMBL464", "ETRETINATE"),
    ("CHEMBL465", "DRONABINOL"),
    ("CHEMBL467", "HYDROXYUREA"),
    ("CHEMBL468", "THALIDOMIDE"),
    ("CHEMBL469", "KETOROLAC"),
    ("CHEMBL470", "P-HYDROXY KETOROLAC"),
    ("CHEMBL471", "SOTALOL"),
    ("CHEMBL472", "GLYBURIDE"),
    ("CHEMBL473", "DOFETILIDE"),
    ("CHEMBL475", "N-DESETHYL DORZOLAMIDE"),
    ("CHEMBL476", "DACARBAZINE"),
    ("CHEMBL477", "ADENOSINE"),
    ("CHEMBL478", "CHLOROPHENYLPIPERAZINE"),
    ("CHEMBL479", "THIORIDAZINE"),
    ("CHEMBL480", "LANSOPRAZOLE"),
    ("CHEMBL481", "IRINOTECAN"),
    ("CHEMBL483", "TENOFOVIR ANHYDROUS"),
    ("CHEMBL484", "ADEFOVIR"),
    ("CHEMBL485", "CODEINE"),
    ("CHEMBL486", "4'-HYDROXYTAMOXIFEN"),
    ("CHEMBL487", "DROLOXIFENE"),
    ("CHEMBL488", "AMINOGLUTETHIMIDE"),
    ("CHEMBL489", "AFIMOXIFENE"),
    ("CHEMBL490", "PAROXETINE"),
    ("CHEMBL491", "HYDROXYFLUTAMIDE"),
    ("CHEMBL492", "ETIDOCAINE"),
    ("CHEMBL493", "BROMOCRIPTINE"),
    ("CHEMBL494", "ILOPROST"),
    ("CHEMBL495", "ALPROSTADIL"),
    ("CHEMBL496", "HEXACHLOROPHENE"),
    ("CHEMBL497", "CLIOQUINOL"),
    ("CHEMBL498", "CHLORPROPAMIDE"),
    ("CHEMBL499", "TIMOLOL"),
    ("CHEMBL500", "PINDOLOL"),
    ("CHEMBL501", "AMPHETAMINE SULFATE"),
    ("CHEMBL502", "DONEPEZIL"),
    ("CHEMBL503", "LOVASTATIN"),
    ("CHEMBL504", "DIMETHYL SULFOXIDE"),
    ("CHEMBL505", "CHLORPHENIRAMINE"),
    ("CHEMBL506", "PRIMAQUINE"),
    ("CHEMBL507", "N-METHYLHISTAMINE"),
    ("CHEMBL509", "MECLOFENAMIC ACID"),
    ("CHEMBL511", "PYRILAMINE"),
    ("CHEMBL513", "CARMUSTINE"),
    ("CHEMBL514", "LOMUSTINE"),
    ("CHEMBL515", "CHLORAMBUCIL"),
    ("CHEMBL516", "CYPROHEPTADINE"),
    ("CHEMBL517", "DISOPYRAMIDE"),
    ("CHEMBL518", "CHLORPHENACYL"),
    ("CHEMBL520", "XANTHENE CARBOXYLIC ACID"),
    ("CHEMBL521", "IBUPROFEN"),
    ("CHEMBL522", "BENZYLAMINE"),
    ("CHEMBL523", "NORDAZEPAM"),
    ("CHEMBL524", "METHOXAMINE"),
    ("CHEMBL525", "PHOSPHORAMIDE MUSTARD"),
    ("CHEMBL526", "PROPOFOL"),
    ("CHEMBL527", "PIROXICAM"),
    ("CHEMBL528", "CEFTIZOXIME"),
    ("CHEMBL529", "AZITHROMYCIN"),
    ("CHEMBL530", "AMDINOCILLIN"),
    ("CHEMBL531", "PERGOLIDE"),
    ("CHEMBL532", "ERYTHROMYCIN"),
    ("CHEMBL533", "IBUTILIDE"),
    ("CHEMBL534", "KETOTIFEN"),
    ("CHEMBL535", "SUNITINIB"),
    ("CHEMBL537", "HYDROQUINONE"),
    ("CHEMBL538", "ANILINE"),
    ("CHEMBL539", "ACETIC ACID"),
    ("CHEMBL540", "IMIDAZOLE"),
    ("CHEMBL541", "BENZOIC ACID"),
    ("CHEMBL542", "AMINOBENZOIC ACID"),
    ("CHEMBL543", "1-METHYLIMIDAZOLE"),
    ("CHEMBL544", "MEQUINOL"),
    ("CHEMBL545", "ALCOHOL"),
    ("CHEMBL546", "OXPRENOLOL"),
    ("CHEMBL547", "ISOTRETINOIN"),
    ("CHEMBL548", "DINOPROSTONE"),
    ("CHEMBL549", "CITALOPRAM"),
    ("CHEMBL550", "PILOCARPINE"),
    ("CHEMBL553", "ERLOTINIB"),
    ("CHEMBL554", "LAPATINIB"),
    ("CHEMBL556", "DEFEROXAMINE"),
    ("CHEMBL557", "DETROTHYRONINE"),
    ("CHEMBL558", "MEXILETINE"),
    ("CHEMBL559", "DEXTROTHYROXINE"),
    ("CHEMBL561", "LOMEFLOXACIN"),
    ("CHEMBL562", "GRISEOFULVIN"),
    ("CHEMBL563", "FLURBIPROFEN"),
    ("CHEMBL564", "PROMAZINE"),
    ("CHEMBL565", "CLOFIBRATE"),
    ("CHEMBL566", "URACIL"),
    ("CHEMBL567", "PERPHENAZINE"),
    ("CHEMBL568", "OXAZEPAM"),
    ("CHEMBL569", "PROCAINE"),
    ("CHEMBL570", "TRIFLUPROMAZINE"),
    ("CHEMBL571", "KETOPROFEN"),
    ("CHEMBL572", "NITROFURANTOIN"),
    ("CHEMBL573", "NIACIN"),
    ("CHEMBL574", "P-TOLUENESULFONAMIDE"),
    ("CHEMBL575", "METHICILLIN"),
    ("CHEMBL576", "SUCCINIC ACID"),
    ("CHEMBL577", "ENALAPRILAT ANHYDROUS"),
    ("CHEMBL578", "ENALAPRIL"),
    ("CHEMBL579", "SPIRAPRILAT"),
    ("CHEMBL580", "LORAZEPAM"),
    ("CHEMBL581", "FOSINOPRILAT"),
    ("CHEMBL582", "ISOPROPYL ALCOHOL"),
    ("CHEMBL583", "GREPAFLOXACIN"),
    ("CHEMBL584", "NELFINAVIR"),
    ("CHEMBL585", "TRIAMTERENE"),
    ("CHEMBL586", "SALICYLURIC ACID"),
    ("CHEMBL587", "SKF-89124A"),
    ("CHEMBL588", "FENOLDOPAM"),
    ("CHEMBL589", "ROPINIROLE"),
    ("CHEMBL590", "MENADIONE"),
    ("CHEMBL591", "ETHCHLORVYNOL"),
    ("CHEMBL592", "LEVORPHANOL"),
    ("CHEMBL593", "DELAVIRDINE"),
    ("CHEMBL594", "EMEDASTINE"),
    ("CHEMBL595", "PIOGLITAZONE"),
    ("CHEMBL596", "FENTANYL"),
    ("CHEMBL597", "PHENTOLAMINE"),
    ("CHEMBL599", "MELOXICAM"),
    ("CHEMBL600", "ACETYLCYSTEINE"),
    ("CHEMBL601", "AMINOLEVULINIC ACID"),
    ("CHEMBL602", "CYSTEAMINE"),
    ("CHEMBL603", "ZAFIRLUKAST"),
    ("CHEMBL604", "CUPRIC SULFATE"),
    ("CHEMBL605", "PROCAINAMIDE HYDROCHLORIDE"),
    ("CHEMBL606", "MISOPROSTOL"),
    ("CHEMBL607", "MEPERIDINE"),
    ("CHEMBL608", "PROBUCOL"),
    ("CHEMBL609", "TRIENTINE"),
    ("CHEMBL610", "PHENETHYLAMINE"),
    ("CHEMBL611", "TERAZOSIN"),
    ("CHEMBL612", "DEXTROAMPHETAMINE"),
    ("CHEMBL613", "PYRAZINOIC ACID"),
    ("CHEMBL614", "PYRAZINAMIDE"),
    ("CHEMBL615", "PENICILLIN V"),
    ("CHEMBL616", "MONODEETHYLATED-MCP"),
    ("CHEMBL617", "CEPHALOTHIN"),
    ("CHEMBL618", "4-CHLORO-BENZOIC ACID"),
    ("CHEMBL619", "3-METHYLXANTHINE"),
    ("CHEMBL620", "CLIDINIUM"),
    ("CHEMBL621", "TRAZODONE"),
    ("CHEMBL622", "ETODOLAC"),
    ("CHEMBL623", "NEFAZODONE"),
    ("CHEMBL624", "2-[(2-METHYLAMINOETHYL)(P-METHOXYBENZYL)AMINO]PYRIDINE"),
    ("CHEMBL625", "THIABENDAZOLE"),
    ("CHEMBL626", "NAFTIFINE"),
    ("CHEMBL627", "AMITRIPTYLINOXIDE"),
    ("CHEMBL628", "PENTOXIFYLLINE"),
    ("CHEMBL629", "AMITRIPTYLINE"),
    ("CHEMBL630", "N-DEALKYL NAFTIFINE"),
    ("CHEMBL631", "PROPAFENONE"),
    ("CHEMBL632", "BETAMETHASONE"),
    ("CHEMBL633", "AMIODARONE"),
    ("CHEMBL634", "ALFENTANIL"),
    ("CHEMBL635", "PREDNISONE"),
    ("CHEMBL636", "RIVASTIGMINE"),
    ("CHEMBL637", "VENLAFAXINE"),
    ("CHEMBL638", "VORICONAZOLE"),
    ("CHEMBL639", "AZELASTINE"),
    ("CHEMBL640", "PROCAINAMIDE"),
    ("CHEMBL641", "ATOMOXETINE"),
    ("CHEMBL642", "ACEBUTOLOL"),
    ("CHEMBL643", "PROMETHAZINE"),
    ("CHEMBL644", "TRIMIPRAMINE"),
    ("CHEMBL645", "BISOPROLOL"),
    ("CHEMBL646", "TRIAZOLAM"),
    ("CHEMBL647", "APRACLONIDINE"),
    ("CHEMBL648", "CYCLIZINE"),
    ("CHEMBL650", "METHYLPREDNISOLONE"),
    ("CHEMBL651", "METHADONE"),
    ("CHEMBL652", "FLECAINIDE"),
    ("CHEMBL654", "MIRTAZAPINE"),
    ("CHEMBL655", "MIDAZOLAM"),
    ("CHEMBL656", "OXYCODONE"),
    ("CHEMBL657", "DIPHENHYDRAMINE"),
    ("CHEMBL658", "SUFENTANIL"),
    ("CHEMBL659", "GALANTAMINE"),
    ("CHEMBL660", "AMANTADINE"),
    ("CHEMBL661", "ALPRAZOLAM"),
    ("CHEMBL663", "M-PHENOXYBENZOIC ACID FOR CIS-ISOMER"),
    ("CHEMBL665", "N-METHYL PYRROLIDINE (NMP)"),
    ("CHEMBL666", "FOSCARNET"),
    ("CHEMBL667", "ACETYLCHOLINE"),
    ("CHEMBL668", "PROTRIPTYLINE"),
    ("CHEMBL669", "CYCLOBENZAPRINE"),
    ("CHEMBL670", "TEPA"),
    ("CHEMBL671", "THIOTEPA"),
    ("CHEMBL672", "FENOFIBRATE"),
    ("CHEMBL673", "PARGYLINE"),
    ("CHEMBL674", "OSELTAMIVIR CARBOXYLATE"),
    ("CHEMBL675", "ALENDRONATE SODIUM"),
    ("CHEMBL677", "LEVONORDEFRIN"),
    ("CHEMBL679", "EPINEPHRINE"),
    ("CHEMBL680", "CEFACLOR ANHYDROUS"),
    ("CHEMBL681", "ETOMIDATE"),
    ("CHEMBL682", "AMODIAQUINE"),
    ("CHEMBL683", "CLOFIBRIC ACID"),
    ("CHEMBL684", "DIETHYLCARBAMAZINE"),
    ("CHEMBL685", "MEBENDAZOLE"),
    ("CHEMBL686", "MEFENAMIC ACID"),
    ("CHEMBL687", "ACETYLSULFANILAMIDE"),
    ("CHEMBL688", "FENTANYL CITRATE"),
    ("CHEMBL689", "MANNITOL"),
    ("CHEMBL690", "PRAVASTATIN SODIUM"),
    ("CHEMBL691", "ETHINYL ESTRADIOL"),
    ("CHEMBL692", "GLYCERIN"),
    ("CHEMBL695", "TRIMETHADIONE"),
    ("CHEMBL696", "ETHOSUXIMIDE"),
    ("CHEMBL697", "METHSUXIMIDE"),
    ("CHEMBL698", "TETRACAINE"),
    ("CHEMBL699", "ETOFYLLINE"),
    ("CHEMBL700", "SULFAPYRIDINE"),
    ("CHEMBL701", "BACLOFEN"),
    ("CHEMBL702", "PIPERACILLIN"),
    ("CHEMBL703", "SUXAMETHONIUM"),
    ("CHEMBL704", "MESALAMINE"),
    ("CHEMBL705", "ALITRETINOIN"),
    ("CHEMBL706", "CETYL ALCOHOL"),
    ("CHEMBL707", "DOXAZOSIN"),
    ("CHEMBL708", "ZIPRASIDONE"),
    ("CHEMBL709", "ALFUZOSIN"),
    ("CHEMBL710", "FINASTERIDE"),
    ("CHEMBL711", "PHENINDIONE"),
    ("CHEMBL712", "ANISINDIONE"),
    ("CHEMBL713", "ENTECAVIR ANHYDROUS"),
    ("CHEMBL714", "ALBUTEROL"),
    ("CHEMBL715", "OLANZAPINE"),
    ("CHEMBL716", "QUETIAPINE"),
    ("CHEMBL717", "MEDROXYPROGESTERONE ACETATE"),
    ("CHEMBL718", "METHYLDOPA (RACEMIC)"),
    ("CHEMBL719", "MUPIROCIN"),
    ("CHEMBL720", "BENZYL ALCOHOL"),
    ("CHEMBL721", "ACROLEIN"),
    ("CHEMBL722", "PROPYNAL"),
    ("CHEMBL723", "CARVEDILOL"),
    ("CHEMBL724", "2-PIPERAZIN-1-YL-PYRIMIDINE"),
    ("CHEMBL726", "FLUPHENAZINE"),
    ("CHEMBL727", "THIOGUANINE"),
    ("CHEMBL728", "PROCHLORPERAZINE"),
    ("CHEMBL729", "LOPINAVIR"),
    ("CHEMBL730", "NITROGLYCERIN"),
    ("CHEMBL731", "4-HYDROXYCYCLOPHOSPHAMIDE"),
    ("CHEMBL732", "7-ACETYLAMINOETHYL-AMINO-FLUOROQUINONE"),
    ("CHEMBL733", "ALDOIFOSFAMIDE"),
    ("CHEMBL734", "ACETOHYDROXAMIC ACID"),
    ("CHEMBL735", "3-OXO-1-PIPERAZINYL-NORFLOXACIN"),
    ("CHEMBL736", "7-DESETHYL-NORFLOXACIN"),
    ("CHEMBL737", "7-AMINO-FLUOROQUINONE"),
    ("CHEMBL738", "THIOPENTAL SODIUM"),
    ("CHEMBL739", "4-N-ACETYL-1-PIPERAZINYL-NORFLOXACIN"),
    ("CHEMBL740", "4-N-FORMYL-1-PIPERAZINYL-NORFLOXACIN"),
    ("CHEMBL741", "LAMOTRIGINE"),
    ("CHEMBL742", "KETAMINE"),
    ("CHEMBL743", "CARBOXYLIC ACID METABOLITE OF CELECOXIB"),
    ("CHEMBL744", "RILUZOLE"),
    ("CHEMBL745", "PRIMARY ALCOHOL METABOLITE OF CELECOXIB"),
    ("CHEMBL746", "NEDOCROMIL"),
    ("CHEMBL747", "CYCLOGUANIL"),
    ("CHEMBL748", "PRALIDOXIME CHLORIDE"),
    ("CHEMBL750", "ZONISAMIDE"),
    ("CHEMBL752", "ADENOSINE PHOSPHATE"),
    ("CHEMBL753", "PHENOXYBENZAMINE"),
    ("CHEMBL754", "FOSCARNET SODIUM"),
    ("CHEMBL757", "NANDROLONE"),
    ("CHEMBL760", "ANAGRELIDE"),
    ("CHEMBL761", "NAPHAZOLINE"),
    ("CHEMBL762", "OXYMETAZOLINE"),
    ("CHEMBL764", "NORDEFRIN"),
    ("CHEMBL765", "GUANETHIDINE"),
    ("CHEMBL766", "CILASTATIN"),
    ("CHEMBL768", "ESMOLOL"),
    ("CHEMBL769", "4-(2-HYDROXY-3-ISOPROPYL-AMINOPROPOXY)BENZOIC ACID"),
    ("CHEMBL770", "TOLAZOLINE"),
    ("CHEMBL771", "CYCLOSERINE"),
    ("CHEMBL772", "RESERPINE"),
    ("CHEMBL773", "GLYCINE"),
    ("CHEMBL774", "NORMETANEPHRINE"),
    ("CHEMBL775", "METANEPHRINE"),
    ("CHEMBL776", "METAPROTERENOL"),
    ("CHEMBL777", "CLAVULANIC ACID"),
    ("CHEMBL778", "DEXMEDETOMIDINE"),
    ("CHEMBL779", "TADALAFIL"),
    ("CHEMBL780", "PENTETIC ACID"),
    ("CHEMBL781", "MAZINDOL"),
    ("CHEMBL782", "TOLBUTAMIDE"),
    ("CHEMBL783", "NATEGLINIDE"),
    ("CHEMBL784", "IMIDAZOLE ACETIC ACID"),
    ("CHEMBL786", "TAMOXIFEN CITRATE"),
    ("CHEMBL787", "MONTELUKAST"),
    ("CHEMBL788", "IDOXURIDINE"),
    ("CHEMBL789", "RATHYRONINE"),
    ("CHEMBL790", "CHLORHEXIDINE"),
    ("CHEMBL792", "URIC ACID"),
    ("CHEMBL796", "METHYLPHENIDATE"),
    ("CHEMBL797", "PHENSUXIMIDE"),
    ("CHEMBL799", "CILOSTAZOL"),
    ("CHEMBL802", "MINOXIDIL"),
    ("CHEMBL803", "CYTARABINE"),
    ("CHEMBL804", "P-CHLOROBENZENESULFONAMIDE"),
    ("CHEMBL806", "FLUTAMIDE"),
    ("CHEMBL807", "MEMANTINE"),
    ("CHEMBL808", "ECONAZOLE"),
    ("CHEMBL809", "SERTRALINE"),
    ("CHEMBL810", "TEMOZOLOMIDE"),
    ("CHEMBL811", "BROMPHENIRAMINE"),
    ("CHEMBL812", "PYRIDOSTIGMINE BROMIDE"),
    ("CHEMBL813", "EPROSARTAN"),
    ("CHEMBL814", "FLUVOXAMINE"),
    ("CHEMBL815", "DINOPROST"),
    ("CHEMBL816", "ETHYLENEDIAMINE"),
    ("CHEMBL817", "TOLAZAMIDE"),
    ("CHEMBL818", "IOBENGUANE"),
    ("CHEMBL819", "OXACILLIN"),
    ("CHEMBL820", "BUSULFAN"),
    ("CHEMBL821", "GUANIDINE"),
    ("CHEMBL822", "TERBINAFINE"),
    ("CHEMBL823", "CHLOROPROMAZINE SULFOXIDE"),
    ("CHEMBL824", "NOR2-CHLORPROMAZINE"),
    ("CHEMBL825", "NOR1-CHLORPROMAZINE"),
    ("CHEMBL826", "ENOXACIN"),
    ("CHEMBL827", "DEXMETHYLPHENIDATE"),
    ("CHEMBL828", "PHENOTHIAZINE"),
    ("CHEMBL829", "METHYLPROMAZINE"),
    ("CHEMBL830", "EFLORNITHINE"),
    ("CHEMBL831", "LOXAPINE"),
    ("CHEMBL832", "SULFINPYRAZONE"),
    ("CHEMBL833", "TICLOPIDINE"),
    ("CHEMBL834", "PAMIDRONIC ACID"),
    ("CHEMBL836", "TAMSULOSIN"),
    ("CHEMBL837", "7-ETHYL-10-HYDROXYCAMPTOTHECIN"),
    ("CHEMBL838", "BENAZEPRIL"),
    ("CHEMBL839", "CARTEOLOL"),
    ("CHEMBL840", "4-CHLOROPHENYLBIGUANIDE"),
    ("CHEMBL841", "LOPERAMIDE"),
    ("CHEMBL842", "CHLOROTHIAZIDE"),
    ("CHEMBL843", "ROSIGLITAZONE MALEATE"),
    ("CHEMBL844", "BRIMONIDINE"),
    ("CHEMBL845", "N-DESMETHYLCLOZAPINE"),
    ("CHEMBL846", "CALCITRIOL"),
    ("CHEMBL847", "OXAMNIQUINE"),
    ("CHEMBL848", "LENALIDOMIDE"),
    ("CHEMBL849", "TRICLOSAN"),
    ("CHEMBL850", "SPARFLOXACIN"),
    ("CHEMBL851", "PHENYL PROPIONIC ACID"),
    ("CHEMBL852", "MELPHALAN"),
    ("CHEMBL853", "ZALCITABINE"),
    ("CHEMBL855", "TRIPROLIDINE"),
    ("CHEMBL856", "PRIMIDONE"),
    ("CHEMBL857", "BIOTIN"),
    ("CHEMBL858", "EDETIC ACID"),
    ("CHEMBL859", "OXYPURINOL"),
    ("CHEMBL860", "E-DOXEPIN"),
    ("CHEMBL861", "MEPHENYTOIN"),
    ("CHEMBL862", "GUANFACINE"),
    ("CHEMBL863", "CYSTEINE"),
    ("CHEMBL864", "CARBINOXAMINE"),
    ("CHEMBL865", "VALDECOXIB"),
    ("CHEMBL866", "MYCOPHENOLIC ACID"),
    ("CHEMBL867", "IOPANOIC ACID"),
    ("CHEMBL869", "NITROFURAZONE"),
    ("CHEMBL870", "ALENDRONIC ACID"),
    ("CHEMBL871", "ETIDRONIC ACID"),
    ("CHEMBL872", "4-UREIDOETODOLAC"),
    ("CHEMBL873", "6-HYDROXYETODOLAC"),
    ("CHEMBL874", "8-(1-HYDROXYETHYL)ETODOLAC"),
    ("CHEMBL875", "7-HYDROXYETODOLAC"),
    ("CHEMBL877", "TRANEXAMIC ACID"),
    ("CHEMBL878", "METOLAZONE"),
    ("CHEMBL879", "6-DEOXY PENCICLOVIR"),
    ("CHEMBL880", "FAMCICLOVIR"),
    ("CHEMBL881", "MONOACETYL-6-DEOXY PENCICLOVIR"),
    ("CHEMBL885", "EMTRICITABINE"),
    ("CHEMBL886", "5-FLUORODEOXYURIDYLATE"),
    ("CHEMBL887", "RASAGILINE"),
    ("CHEMBL888", "GEMCITABINE"),
    ("CHEMBL889", "PALIFOSFAMIDE"),
    ("CHEMBL891", "CLOXACILLIN"),
    ("CHEMBL892", "UFIPRAZOLE"),
    ("CHEMBL893", "DICLOXACILLIN"),
    ("CHEMBL894", "BUPROPION"),
    ("CHEMBL895", "NALBUPHINE"),
    ("CHEMBL896", "HYDROXYZINE"),
    ("CHEMBL897", "PROBENECID"),
    ("CHEMBL898", "DIFLUNISAL"),
    ("CHEMBL899", "LANSOPRAZOLE SULFIDE"),
    ("CHEMBL900", "ORPHENADRINE"),
    ("CHEMBL902", "FAMOTIDINE"),
    ("CHEMBL903", "HYDRAZINECARBOXAMIDE"),
    ("CHEMBL904", "DEXMETHYLPHENIDATE HYDROCHLORIDE"),
    ("CHEMBL905", "RIZATRIPTAN"),
    ("CHEMBL906", "MINOXIDIL SULFATE"),
    ("CHEMBL907", "CARBOXYLIC ACID METABOLITE"),
    ("CHEMBL908", "CHLORPROTHIXENE"),
    ("CHEMBL909", "7-HYDROXYCHLORPROMAZINE"),
    ("CHEMBL911", "ZOLPIDEM"),
    ("CHEMBL912", "FLUMAZENIL METHYLESTER"),
    ("CHEMBL913", "NORNITROGEN MUSTARD"),
    ("CHEMBL914", "FEXOFENADINE"),
    ("CHEMBL915", "NEDOCROMIL SODIUM"),
    ("CHEMBL916", "TIROFIBAN"),
    ("CHEMBL917", "FLOXURIDINE"),
    ("CHEMBL918", "PHENACEMIDE"),
    ("CHEMBL919", "FOSPHENYTOIN SODIUM"),
    ("CHEMBL920", "CHOLINE"),
    ("CHEMBL922", "ADEFOVIR DIPIVOXIL"),
    ("CHEMBL923", "RISEDRONIC ACID"),
    ("CHEMBL924", "ZOLEDRONIC ACID ANHYDROUS"),
    ("CHEMBL925", "TYROSINE"),
    ("CHEMBL926", "DOBUTAMINE"),
    ("CHEMBL927", "CEFDINIR"),
    ("CHEMBL928", "DANTROLENE SODIUM"),
    ("CHEMBL929", "DELAVIRDINE MESYLATE"),
    ("CHEMBL930", "GLUTAMINE"),
    ("CHEMBL931", "HALOTHANE"),
    ("CHEMBL932", "DIPYRIDAMOLE"),
    ("CHEMBL933", "METYRAPOL"),
    ("CHEMBL934", "METYRAPONE"),
    ("CHEMBL936", "DIPHENIDOL"),
    ("CHEMBL937", "DIETHYLCARBAMAZINE CITRATE"),
    ("CHEMBL938", "SARALASIN"),
    ("CHEMBL939", "GEFITINIB"),
    ("CHEMBL940", "GABAPENTIN"),
    ("CHEMBL941", "IMATINIB"),
    ("CHEMBL942", "BISACODYL"),
    ("CHEMBL944", "CHLOROPROCAINE HYDROCHLORIDE"),
    ("CHEMBL945", "AMILORIDE"),
    ("CHEMBL946", "AZATADINE"),
    ("CHEMBL948", "2-NAPHTHYLACETIC ACID"),
    ("CHEMBL950", "BENZOYL FORMIC ACID"),
    ("CHEMBL951", "IOPHENDYLATE"),
    ("CHEMBL952", "DIKETOPIPERAZINE DERIVATIVE OF QUINAPRIL"),
    ("CHEMBL953", "ENTACAPONE"),
    ("CHEMBL954", "ENCLOMIPHENE"),
    ("CHEMBL955", "3'-METHOXY-4'HYDROXYCLOMIPHENE"),
    ("CHEMBL956", "SUPROFEN"),
    ("CHEMBL957", "BOSENTAN"),
    ("CHEMBL958", "3-HYDROXYRIMANTADINE"),
    ("CHEMBL959", "RIMANTADINE"),
    ("CHEMBL960", "LEFLUNOMIDE"),
    ("CHEMBL961", "DITIOCARB"),
    ("CHEMBL962", "EPOPROSTENOL SODIUM"),
    ("CHEMBL963", "OXYMORPHONE"),
    ("CHEMBL964", "DISULFIRAM"),
    ("CHEMBL965", "CARBAMOYLCHOLINE"),
    ("CHEMBL966", "DESMETHYL-OFLOXACIN"),
    ("CHEMBL967", "TEMAZEPAM"),
    ("CHEMBL968", "FLURAZEPAM"),
    ("CHEMBL969", "PRAZEPAM"),
    ("CHEMBL970", "HALAZEPAM"),
    ("CHEMBL971", "PENTOBARBITAL SODIUM"),
    ("CHEMBL972", "SELEGILINE"),
    ("CHEMBL973", "TERIFLUNOMIDE"),
    ("CHEMBL974", "N-DESALKYL-2-OXOQUAZEPAM"),
    ("CHEMBL975", "MESNA"),
    ("CHEMBL976", "PRAZIQUANTEL"),
    ("CHEMBL977", "HYDROCORTISONE HEMISUCCINATE ANHYDROUS"),
    ("CHEMBL978", "METHACHOLINE"),
    ("CHEMBL979", "MEPROBAMATE"),
    ("CHEMBL980", "GUAIFENESIN"),
    ("CHEMBL981", "FENOFIBRIC ACID"),
    ("CHEMBL982", "NALMEFENE"),
    ("CHEMBL983", "SUCCINYLCHOLINE CHLORIDE"),
    ("CHEMBL984", "MIVACURIUM CHLORIDE"),
    ("CHEMBL985", "UREA"),
    ("CHEMBL986", "RETINOL"),
    ("CHEMBL989", "FLUOCINOLONE ACETONIDE"),
    ("CHEMBL990", "BUTENAFINE"),
    ("CHEMBL991", "STAVUDINE"),
    ("CHEMBL992", "N-DESMETHYLDOFETILIDE"),
    ("CHEMBL993", "THYMINE"),
    ("CHEMBL995", "LOSARTAN POTASSIUM"),
    ("CHEMBL996", "CEFOXITIN"),
    ("CHEMBL997", "IBANDRONIC ACID"),
    ("CHEMBL998", "LORATADINE"),
    ("CHEMBL1000", "CETIRIZINE"),
    ("CHEMBL1002", "LEVOSALBUTAMOL"),
    ("CHEMBL1003", "CLAVULANATE POTASSIUM"),
    ("CHEMBL1004", "DOXYLAMINE"),
    ("CHEMBL1005", "REMIFENTANIL"),
    ("CHEMBL1006", "AMIFOSTINE"),
    ("CHEMBL1007", "GONADORELIN"),
    ("CHEMBL1008", "BEPRIDIL"),
    ("CHEMBL1009", "LEVODOPA"),
    ("CHEMBL1010", "CEFOTAXIME SODIUM"),
    ("CHEMBL1011", "METHYLPIPERAZINE"),
    ("CHEMBL1012", "2-PHTHALIMIDOGLUTARAMIC ACID"),
    ("CHEMBL1013", "LORACARBEF ANHYDROUS"),
    ("CHEMBL1014", "CANDESARTAN CILEXETIL"),
    ("CHEMBL1015", "EVANS BLUE FREE ACID"),
    ("CHEMBL1016", "CANDESARTAN"),
    ("CHEMBL1017", "TELMISARTAN"),
    ("CHEMBL1018", "DIENESTROL"),
    ("CHEMBL1020", "TOLMETIN"),
    ("CHEMBL1021", "NEPAFENAC"),
    ("CHEMBL1023", "BEXAROTENE"),
    ("CHEMBL1024", "IFOSFAMIDE"),
    ("CHEMBL1025", "ISOFLUROPHATE"),
    ("CHEMBL1026", "FENOLDOPAM MESYLATE"),
    ("CHEMBL1027", "TIAGABINE"),
    ("CHEMBL1029", "MIGLUSTAT"),
    ("CHEMBL1030", "4'-HYDROXY-DICLOFENAC"),
    ("CHEMBL1031", "5-HYDROXY-DICLOFENAC"),
    ("CHEMBL1032", "4',5-DIHYDROXY-DICLOFENAC"),
    ("CHEMBL1033", "3'-HYDROXY-4'-METHOXY-DICLOFENAC"),
    ("CHEMBL1034", "DICLOFENAC SODIUM"),
    ("CHEMBL1035", "3'-HYDROXY-DICLOFENAC"),
    ("CHEMBL1036", "HYDROXYHALOPERIDOL"),
    ("CHEMBL1037", "GUANADREL"),
    ("CHEMBL1039", "NORKETAMINE"),
    ("CHEMBL1040", "CALCIFEDIOL ANHYDROUS"),
    ("CHEMBL1041", "PHENYLETHYLMALONAMIDE -"),
    ("CHEMBL1042", "CHOLECALCIFEROL"),
    ("CHEMBL1043", "DAPSONE"),
    ("CHEMBL1044", "PHENYLACETIC ACID"),
    ("CHEMBL1045", "PHTHALIC ACID"),
    ("CHEMBL1046", "AMINOCAPROIC ACID"),
    ("CHEMBL1048", "N-DEALKYLATED DERIVATIVE"),
    ("CHEMBL1049", "DECARBOXYLATED DERIVATIVE"),
    ("CHEMBL1050", "LATANOPROST ACID"),
    ("CHEMBL1051", "LATANOPROST"),
    ("CHEMBL1052", "NORMEPERIDINE"),
    ("CHEMBL1054", "TRICHLORMETHIAZIDE"),
    ("CHEMBL1055", "CHLORTHALIDONE"),
    ("CHEMBL1056", "4-OH-ENCLOMIPHENE"),
    ("CHEMBL1057", "FLUORESCEIN"),
    ("CHEMBL1058", "DESCHLOROBENZOYL INDOMETHACIN"),
    ("CHEMBL1059", "PREGABALIN"),
    ("CHEMBL1060", "SODIUM PHOSPHATE, DIBASIC, ANHYDROUS"),
    ("CHEMBL1061", "GLITAZONE"),
    ("CHEMBL1062", "HYDROXYPROGESTERONE"),
    ("CHEMBL1063", "DEACETYLCOLCHICINE"),
    ("CHEMBL1064", "SIMVASTATIN"),
    ("CHEMBL1065", "METHYSERGIDE"),
    ("CHEMBL1066", "(R,R)-TRAMADOL"),
    ("CHEMBL1067", "LICARBAZEPINE"),
    ("CHEMBL1068", "OXCARBAZEPINE"),
    ("CHEMBL1069", "VALSARTAN"),
    ("CHEMBL1070", "NABUMETONE"),
    ("CHEMBL1071", "OXAPROZIN"),
    ("CHEMBL1072", "BUMETANIDE"),
    ("CHEMBL1073", "GLIPIZIDE"),
    ("CHEMBL1075", "MORICIZINE"),
    ("CHEMBL1076", "DESGLYMIDODRINE"),
    ("CHEMBL1077", "BROMFENAC"),
    ("CHEMBL1079", "TIZANIDINE"),
    ("CHEMBL1080", "2-DESMETHYLCOLCHICIN"),
    ("CHEMBL1081", "3-DESMETHYLCOLCHICIN"),
    ("CHEMBL1082", "AMOXICILLIN"),
    ("CHEMBL1084", "5-HYDROXY ROFECOXIB"),
    ("CHEMBL1085", "ACETOPHENAZINE"),
    ("CHEMBL1086", "DIBUCAINE"),
    ("CHEMBL1087", "MEPIVACAINE"),
    ("CHEMBL1088", "MESORIDAZINE"),
    ("CHEMBL1089", "PHENELZINE"),
    ("CHEMBL1090", "VIDARABINE"),
    ("CHEMBL1091", "HYDROCORTISONE ACETATE"),
    ("CHEMBL1092", "TRIHEXYPHENIDYL HYDROCHLORIDE"),
    ("CHEMBL1093", "ARTICAINE"),
    ("CHEMBL1094", "FELBAMATE"),
    ("CHEMBL1095", "ETHOTOIN"),
    ("CHEMBL1096", "AMLEXANOX"),
    ("CHEMBL1097", "ACECAINIDE"),
    ("CHEMBL1098", "BUPIVACAINE"),
    ("CHEMBL1099", "DIMETHADIONE"),
    ("CHEMBL1100", "PARAMETHADIONE"),
    ("CHEMBL1101", "BIPERIDEN"),
    ("CHEMBL1102", "GLUTETHIMIDE"),
    ("CHEMBL1103", "FURAZOLIDONE"),
    ("CHEMBL1104", "EDROPHONIUM"),
    ("CHEMBL1105", "6-METHOXY-2-NAPHTHYLACETIC ACID"),
    ("CHEMBL1106", "EPINASTINE"),
    ("CHEMBL1107", "HALOFANTRINE"),
    ("CHEMBL1108", "DROPERIDOL"),
    ("CHEMBL1109", "SULFAPHENAZOLE"),
    ("CHEMBL1110", "ALOSETRON"),
    ("CHEMBL1111", "AMBRISENTAN"),
    ("CHEMBL1112", "ARIPIPRAZOLE"),
    ("CHEMBL1113", "AMOXAPINE"),
    ("CHEMBL1114", "THEOBROMINE"),
    ("CHEMBL1115", "PYRIDOSTIGMINE"),
    ("CHEMBL1116", "RALOXIFENE HYDROCHLORIDE"),
    ("CHEMBL1117", "IDARUBICIN"),
    ("CHEMBL1118", "DESVENLAFAXINE"),
    ("CHEMBL1119", "N-DESMETHYLVENLAFAXINE"),
    ("CHEMBL1120", "BISMUTH SUBSALICYLATE"),
    ("CHEMBL1121", "SINCALIDE"),
    ("CHEMBL1123", "DICYCLOMINE"),
    ("CHEMBL1124", "DEALKYLATED DIETHYLPROPION"),
    ("CHEMBL1125", "DESMETHYLOLANZAPINE"),
    ("CHEMBL1126", "PENICILLIN G SODIUM"),
    ("CHEMBL1127", "7-HYDROXYTACRINE"),
    ("CHEMBL1128", "EDROPHONIUM CHLORIDE"),
    ("CHEMBL1129", "TRIFLURIDINE"),
    ("CHEMBL1130", "DOXIFLURIDINE"),
    ("CHEMBL1131", "ACITRETIN"),
    ("CHEMBL1133", "OXYBUTYNIN CHLORIDE"),
    ("CHEMBL1134", "DECAMETHONIUM BROMIDE"),
    ("CHEMBL1135", "DIMETHYLAMINOETHANOL"),
    ("CHEMBL1136", "TELITHROMYCIN"),
    ("CHEMBL1137", "4-HYDROXYPROPRANOLOL SULFATE"),
    ("CHEMBL1138", "EZETIMIBE"),
    ("CHEMBL1139", "EPOPROSTENOL"),
    ("CHEMBL1140", "NIACINAMIDE"),
    ("CHEMBL1141", "POTASSIUM IODIDE"),
    ("CHEMBL1142", "4-AMINOPHENOL"),
    ("CHEMBL1143", "2,4-DICHLOROPHENOL"),
    ("CHEMBL1144", "PRAVASTATIN"),
    ("CHEMBL1145", "3-HYDROXY-4-ACETYLAMINOBENZOIC ACID"),
    ("CHEMBL1146", "CEFAMANDOLE"),
    ("CHEMBL1147", "HYDROXYLATED DERIVATIVE"),
    ("CHEMBL1148", "TORSEMIDE"),
    ("CHEMBL1149", "LEVOCARNITINE"),
    ("CHEMBL1152", "PREDNISOLONE ACETATE"),
    ("CHEMBL1153", "DIGOXIGENIN"),
    ("CHEMBL1154", "BENZISOTHIAZOLE-3-YL-PIPERAZINE"),
    ("CHEMBL1155", "BITP-SULFONE"),
    ("CHEMBL1156", "BENZISOTHIAZOLE-3YL-PIPERAZINE SULFOXIDE"),
    ("CHEMBL1157", "ADIPIC ACID"),
    ("CHEMBL1158", "PARAXANTHINE"),
    ("CHEMBL1159", "PINACIDIL ANHYDROUS"),
    ("CHEMBL1160", "NAPHTHOIC ACID"),
    ("CHEMBL1161", "MOMETASONE FUROATE"),
    ("CHEMBL1162", "NORETHINDRONE"),
    ("CHEMBL1163", "ATAZANAVIR"),
    ("CHEMBL1165", "MOEXIPRIL"),
    ("CHEMBL1166", "ARGATROBAN"),
    ("CHEMBL1167", "SPECTINOMYCIN"),
    ("CHEMBL1168", "RAMIPRIL"),
    ("CHEMBL1169", "AMINOSALICYLIC ACID"),
    ("CHEMBL1170", "TESTOSTERONE PROPIONATE"),
    ("CHEMBL1171", "TRICHLORETHANOL"),
    ("CHEMBL1172", "DESLORATADINE"),
    ("CHEMBL1174", "EPTIFIBATIDE"),
    ("CHEMBL1175", "DULOXETINE"),
    ("CHEMBL1176", "2-CHLOROPHENYL-BISPHENYLMETHANE(MAJOR)"),
    ("CHEMBL1177", "PEMOLINE"),
    ("CHEMBL1180", "O-DEMETHYLATED ADAPALENE"),
    ("CHEMBL1181", "4-HYDROXYTRIMETHOPRIM"),
    ("CHEMBL1182", "GLYCINEBETAINE"),
    ("CHEMBL1183", "DIETHYLAMINOETHANOL"),
    ("CHEMBL1184", "ACETYLCHOLINE CHLORIDE"),
    ("CHEMBL1185", "ZOLMITRIPTAN"),
    ("CHEMBL1186", "5-NITRO-2-FUROIC ACID"),
    ("CHEMBL1187", "PHOSPHORIC ACID"),
    ("CHEMBL1188", "ALPHA-HYDROXY-MIDAZOLAM"),
    ("CHEMBL1189", "DIETHYLAMINE"),
    ("CHEMBL1190", "DECAMETHONIUM"),
    ("CHEMBL1191", "SULFAMETHIZOLE"),
    ("CHEMBL1192", "XANTHOTOXOL"),
    ("CHEMBL1193", "PHENIRAMINE"),
    ("CHEMBL1194", "PRILOCAINE"),
    ("CHEMBL1195", "PROPOXYCAINE"),
    ("CHEMBL1196", "PROPARACAINE"),
    ("CHEMBL1197", "HEXYLCAINE"),
    ("CHEMBL1198", "PRAMOXINE"),
    ("CHEMBL1199", "SULFOXIDE METABOLITE"),
    ("CHEMBL1200", "BENOXINATE"),
    ("CHEMBL1201", "THIOTHIXENE"),
    ("CHEMBL1202", "CIPROFLOXACIN HYDROCHLORIDE"),
    ("CHEMBL1203", "ISONICOTINIC ACID"),
    ("CHEMBL1204", "HYDROXYLATED COMPLETELY DELAKYLATED DIETHYLPROPION"),
    ("CHEMBL1205", "NELFINAVIR MESYLATE"),
    ("CHEMBL1206", "ETHOPROPAZINE"),
    ("CHEMBL1207", "TETRAMETHYLENE SULFOXIDE"),
    ("CHEMBL1208", "CINOXACIN"),
    ("CHEMBL1211", "5-HYDROXYPRIMAQUINE"),
    ("CHEMBL1212", "5-HYDROXYDESMETHYLPRIMAQUINE"),
    ("CHEMBL1213", "5,6-DIHYDROXY-8-AMINOQUINOLINE"),
    ("CHEMBL1214", "CARBENICILLIN"),
    ("CHEMBL1215", "PHENYLEPHRINE"),
    ("CHEMBL1217", "HYDROXY PIROXICAM METABOLITE"),
    ("CHEMBL1218", "RAMELTEON"),
    ("CHEMBL1219", "RABEPRAZOLE"),
    ("CHEMBL1220", "TINIDAZOLE"),
    ("CHEMBL1221", "SULCONAZOLE"),
    ("CHEMBL1223", "PENICILLIN G POTASSIUM"),
    ("CHEMBL1224", "ACRIVASTINE"),
    ("CHEMBL1225", "N-ACETYL PENICILLAMINE"),
    ("CHEMBL1226", "AMINODIMETHOXYQUINAZOLINYLPIPERAZINE"),
    ("CHEMBL1227", "NORMORPHINE"),
    ("CHEMBL1228", "OXYPHENBUTAZONE ANHYDROUS"),
    ("CHEMBL1229", "OSELTAMIVIR"),
    ("CHEMBL1230", "LAMIVUDINE TRIPHOSPHATE"),
    ("CHEMBL1231", "OXYBUTYNIN"),
    ("CHEMBL1232", "ERTAPENEM SODIUM"),
    ("CHEMBL1233", "CARISOPRODOL"),
    ("CHEMBL1234", "DEFEROXAMINE MESYLATE"),
    ("CHEMBL1235", "DESETHYL AMODIAQUINE"),
    ("CHEMBL1236", "DESETHYLCHLOROQUINE"),
    ("CHEMBL1237", "LISINOPRIL ANHYDROUS"),
    ("CHEMBL1238", "AZELAIC ACID"),
    ("CHEMBL1239", "BENZYL BENZOATE"),
    ("CHEMBL1240", "PROPANTHELINE BROMIDE"),
    ("CHEMBL1241", "TRIPELENNAMINE"),
    ("CHEMBL1242", "PHENAZOPYRIDINE"),
    ("CHEMBL1243", "SULFABENZAMIDE"),
    ("CHEMBL1244", "3,4-DIHYDROXY-5-NITROBENZALDEHYDE"),
    ("CHEMBL1245", "TRIMETHAPHAN CAMSYLATE"),
    ("CHEMBL1246", "MONO-N-ACETYL DAPSONE"),
    ("CHEMBL1247", "4-AMINO-4'-HYDROXAMINE-DIPHENYLSULPHONE"),
    ("CHEMBL1248", "FLUORIDE ION F-18"),
    ("CHEMBL1250", "1-METHYLXANTHINE"),
    ("CHEMBL1251", "GANIRELIX"),
    ("CHEMBL1252", "ABARELIX"),
    ("CHEMBL1255", "FORMALDEHYDE"),
    ("CHEMBL1256", "ISOFLURANE"),
    ("CHEMBL1257", "ENFLURANE"),
    ("CHEMBL1258", "CARBAMAZEPINE EPOXIDE"),
    ("CHEMBL1259", "METOCURINE"),
    ("CHEMBL1260", "ALPHA-HYDROXYTRIMETHOPRIM"),
    ("CHEMBL1261", "CITRIC ACID"),
    ("CHEMBL1262", "OXICONAZOLE"),
    ("CHEMBL1263", "SALMETEROL"),
    ("CHEMBL1264", "5-HYDROXY PROPAFENONE"),
    ("CHEMBL1265", "ADAPALENE"),
    ("CHEMBL1266", "TETRAHYDROZOLINE"),
    ("CHEMBL1267", "LERIGLITAZONE"),
    ("CHEMBL1271", "PENTOLINIUM"),
    ("CHEMBL1272", "REPAGLINIDE"),
    ("CHEMBL1273", "7-AMINOCLONAZEPAM"),
    ("CHEMBL1274", "NILUTAMIDE"),
    ("CHEMBL1275", "PERGOLIDE MESYLATE"),
    ("CHEMBL1276", "DESMETHYLSELEGILINE"),
    ("CHEMBL1277", "N-{2-[4-(3-AMINO-PYRIDIN-2-YL)-PIPERAZINE-1-CARBONYL]-1H-INDOL-5-YL}-METHANESULFONAMIDE"),
    ("CHEMBL1278", "NARATRIPTAN"),
    ("CHEMBL1279", "FROVATRIPTAN"),
    ("CHEMBL1280", "VERAPAMIL HYDROCHLORIDE"),
    ("CHEMBL1282", "IMIQUIMOD"),
    ("CHEMBL1283", "4-NITROGLUTETHIMIDE"),
    ("CHEMBL1284", "3,4-DIHYDROXYPHENYLACETIC ACID"),
    ("CHEMBL1285", "P-HYDROXYGLUTETHIMIDE"),
    ("CHEMBL1286", "LEVETIRACETAM"),
    ("CHEMBL1288", "NAPHTHALEN-1-YL-METHANOL"),
    ("CHEMBL1289", "HALOPROGIN"),
    ("CHEMBL1290", "PENBUTOLOL"),
    ("CHEMBL1291", "METIPRANOLOL"),
    ("CHEMBL1292", "CLOFAZIMINE"),
    ("CHEMBL1293", "BETA CAROTENE"),
    ("CHEMBL1294", "QUINIDINE"),
    ("CHEMBL1295", "BUTOCONAZOLE"),
    ("CHEMBL1296", "CEFOTIAM"),
    ("CHEMBL1297", "FENOPROFEN"),
    ("CHEMBL1298", "NORVERAPAMIL"),
    ("CHEMBL1301", "HYDROXYSTILBAMIDINE"),
    ("CHEMBL1302", "GLYCINEXYLIDIDE"),
    ("CHEMBL1303", "ROTIGOTINE"),
    ("CHEMBL1304", "ERYTHRO-HYDROBUPROPION"),
    ("CHEMBL1305", "ANTAZOLINE"),
    ("CHEMBL1307", "N-MONODEISOPROPYL DISOPYRAMIDE"),
    ("CHEMBL1308", "FOMEPIZOLE"),
    ("CHEMBL1311", "ISOSORBIDE MONONITRATE"),
    ("CHEMBL1312", "REVERSETRIIODOTHYRONINE"),
    ("CHEMBL1313", "4-HYDROXY-ALPRAZOLAM"),
    ("CHEMBL1314", "TIOPRONIN"),
    ("CHEMBL1316", "CARPROFEN"),
    ("CHEMBL1317", "DIDESMETHYLIMIPRAMINE"),
    ("CHEMBL1319", "4-KETOIFOSFAMIDE"),
    ("CHEMBL1321", "PROCARBAZINE"),
    ("CHEMBL1322", "N-BENZYLPROPARGYLAMINE"),
    ("CHEMBL1323", "DARUNAVIR"),
    ("CHEMBL1324", "TOLCAPONE"),
    ("CHEMBL1328", "PENTAGASTRIN"),
    ("CHEMBL1329", "MORPHINE 3-GLUCURONIDE"),
    ("CHEMBL1330", "MORPHINE GLUCURONIDE"),
    ("CHEMBL1332", "N,N'-DINITROSOPIPERAZINE"),
    ("CHEMBL1333", "N-MONONITROSOPIPERAZINE"),
    ("CHEMBL1334", "N-NITROSODOETHANOLAMINE"),
    ("CHEMBL1335", "PEMOLINE DIONE"),
    ("CHEMBL1336", "SORAFENIB"),
    ("CHEMBL1337", "NITISINONE"),
    ("CHEMBL1338", "N-BENZYLMETHYLAMINE"),
    ("CHEMBL1339", "VARDENAFIL HYDROCHLORIDE"),
    ("CHEMBL1340", "N-DESETHYL BRINZOLAMIDE"),
    ("CHEMBL1341", "METHOXYFLURANE"),
    ("CHEMBL1342", "OXYBATE"),
    ("CHEMBL1343", "1-[4-CARBOXYPROPYL]-3,7-DIMETHYLXANTHINE"),
    ("CHEMBL1344", "OMEPRAZOLE SULFONE"),
    ("CHEMBL1345", "GUANETHIDINE MONOSULFATE"),
    ("CHEMBL1346", "DARIFENACIN"),
    ("CHEMBL1347", "3-O-METHYL-ALPHA-METHYLDOPAMINE"),
    ("CHEMBL1349", "VALACYCLOVIR"),
    ("CHEMBL1350", "TILUDRONIC ACID"),
    ("CHEMBL1351", "CARBOPLATIN"),
    ("CHEMBL1352", "NITRIC ACID"),
    ("CHEMBL1353", "SODIUM BICARBONATE"),
    ("CHEMBL1354", "SODIUM ACETATE"),
    ("CHEMBL1355", "SODIUM CITRATE"),
    ("CHEMBL1356", "SODIUM BENZOATE"),
    ("CHEMBL1357", "SODIUM LACTATE"),
    ("CHEMBL1358", "FULVESTRANT"),
    ("CHEMBL1359", "ERTAPENEM"),
    ("CHEMBL1360", "ATRACURIUM"),
    ("CHEMBL1362", "FLUORIDE ION"),
    ("CHEMBL1363", "ARFORMOTEROL"),
    ("CHEMBL1364", "PYRIDOXINE"),
    ("CHEMBL1365", "N-DEPROPYL-PROPAPHENONE"),
    ("CHEMBL1366", "AURANOFIN"),
    ("CHEMBL1367", "4-EN-METABOLITE"),
    ("CHEMBL1368", "SODIUM PHOSPHATE, MONOBASIC"),
    ("CHEMBL1370", "BUDESONIDE"),
    ("CHEMBL1371", "CHLORZOXAZONE"),
    ("CHEMBL1372", "OXIGLUTATIONE"),
    ("CHEMBL1373", "MODAFINIL"),
    ("CHEMBL1374", "2-{3-[HYDROXY(PHENYL)METHYL]PHENYL}PROPANOIC ACID"),
    ("CHEMBL1375", "5-CHLOROSALICYLIC ACID"),
    ("CHEMBL1376", "SULINDAC SULFOXIDE"),
    ("CHEMBL1377", "PROGUANIL"),
    ("CHEMBL1378", "THIETHYLPERAZINE"),
    ("CHEMBL1379", "TETRAHYDROTHIOPHENE"),
    ("CHEMBL1380", "ABACAVIR"),
    ("CHEMBL1381", "O-TOLYLAMINE"),
    ("CHEMBL1382", "TOLTERODINE"),
    ("CHEMBL1383", "DDA-TRIPHOSPHATE"),
    ("CHEMBL1384", "KANAMYCIN"),
    ("CHEMBL1386", "TRANSPLATIN"),
    ("CHEMBL1387", "NORETHYNODREL"),
    ("CHEMBL1388", "MONOBENZONE"),
    ("CHEMBL1389", "LEVONORGESTREL"),
    ("CHEMBL1391", "O,P'-DDE (1,1-(O,P'-DICHLORODIPHENYL)-2,2 DICHLOROETHENE)"),
    ("CHEMBL1392", "2,4-DIHYDROXYBENZOPHENONE"),
    ("CHEMBL1393", "SPIRONOLACTONE"),
    ("CHEMBL1394", "4'-HYDROXYFLURBIPROFEN"),
    ("CHEMBL1395", "METHYLTESTOSTERONE"),
    ("CHEMBL1397", "POSACONAZOLE"),
    ("CHEMBL1398", "ALPHA-PHENYL-GAMMA-BUTYROLACTONE"),
    ("CHEMBL1399", "ANASTROZOLE"),
    ("CHEMBL1400", "O-DESMETHYL TRAMADOL"),
    ("CHEMBL1401", "NITAZOXANIDE"),
    ("CHEMBL1402", "4-HYDROXYTORMIFENE"),
    ("CHEMBL1403", "PHENYLGLYCINE"),
    ("CHEMBL1404", "RANOLAZINE"),
    ("CHEMBL1405", "ESTRONE"),
    ("CHEMBL1407", "LAUDANOSINE"),
    ("CHEMBL1409", "FLUVOXAMINE MALEATE"),
    ("CHEMBL1410", "NONOXYNOL 9"),
    ("CHEMBL1411", "LISOFYLLINE"),
    ("CHEMBL1412", "PIPERAZINE"),
    ("CHEMBL1413", "CICLOPIROX"),
    ("CHEMBL1414", "SYRINGIC ACID"),
    ("CHEMBL1419", "SIBUTRAMINE"),
    ("CHEMBL1420", "PRALIDOXIME"),
    ("CHEMBL1421", "DASATINIB ANHYDROUS"),
    ("CHEMBL1422", "SITAGLIPTIN"),
    ("CHEMBL1423", "PIMOZIDE"),
    ("CHEMBL1424", "XANTHINE"),
    ("CHEMBL1425", "MERCAPTOPURINE ANHYDROUS"),
    ("CHEMBL1427", "HYPOXANTHINE"),
    ("CHEMBL1428", "NIMODIPINE"),
    ("CHEMBL1429", "DESMOPRESSIN"),
    ("CHEMBL1430", "PENICILLAMINE"),
    ("CHEMBL1431", "METFORMIN"),
    ("CHEMBL1432", "2,3-DIHYDROXYBENZOIC ACID"),
    ("CHEMBL1433", "DOXYCYCLINE ANHYDROUS"),
    ("CHEMBL1434", "MINOCYCLINE"),
    ("CHEMBL1435", "CEFAZOLIN"),
    ("CHEMBL1436", "CEFUROXIME"),
    ("CHEMBL1437", "NOREPINEPHRINE"),
    ("CHEMBL1439", "TAZOBACTAM SODIUM"),
    ("CHEMBL1440", "TETRACYCLINE"),
    ("CHEMBL1441", "ETHIONAMIDE"),
    ("CHEMBL1442", "MTIC"),
    ("CHEMBL1443", "NAFCILLIN"),
    ("CHEMBL1444", "LETROZOLE"),
    ("CHEMBL1445", "FLUOXYMESTERONE"),
    ("CHEMBL1446", "KANAMYCIN SULFATE"),
    ("CHEMBL1447", "LINCOMYCIN"),
    ("CHEMBL1448", "NICLOSAMIDE"),
    ("CHEMBL1449", "TICARCILLIN"),
    ("CHEMBL1450", "ATOVAQUONE"),
    ("CHEMBL1451", "TRIAMCINOLONE"),
    ("CHEMBL1453", "DIGITOXIGENIN"),
    ("CHEMBL1454", "LEVAMISOLE"),
    ("CHEMBL1455", "ALTRETAMINE"),
    ("CHEMBL1456", "MYCOPHENOLATE MOFETIL"),
    ("CHEMBL1457", "HYDROCODONE"),
    ("CHEMBL1458", "1,3-DICYCLOHEXYLUREA"),
    ("CHEMBL1459", "N-DESMETHYL LEVOFLOXACIN"),
    ("CHEMBL1460", "DIDANOSINE"),
    ("CHEMBL1461", "GENTISIC ACID"),
    ("CHEMBL1463", "FLUCYTOSINE"),
    ("CHEMBL1464", "WARFARIN"),
    ("CHEMBL1465", "PHENPROCOUMON"),
    ("CHEMBL1466", "DICUMAROL"),
    ("CHEMBL1467", "ALLOPURINOL"),
    ("CHEMBL1469", "PHENYLBUTANOIC ACID"),
    ("CHEMBL1471", "APREPITANT"),
    ("CHEMBL1472", "PROTIRELIN"),
    ("CHEMBL1473", "FLUTICASONE PROPIONATE"),
    ("CHEMBL1475", "TRIOXSALEN"),
    ("CHEMBL1477", "CERIVASTATIN"),
    ("CHEMBL1478", "LITHOCHOLIC ACID"),
    ("CHEMBL1479", "DANAZOL"),
    ("CHEMBL1480", "FELODIPINE"),
    ("CHEMBL1481", "GLIMEPIRIDE"),
    ("CHEMBL1482", "BETHANECHOL"),
    ("CHEMBL1483", "ALBENDAZOLE"),
    ("CHEMBL1484", "NICARDIPINE"),
    ("CHEMBL1485", "ARGININE"),
    ("CHEMBL1486", "TENOFOVIR DISOPROXIL FUMARATE"),
    ("CHEMBL1487", "ATORVASTATIN"),
    ("CHEMBL1488", "URACIL MUSTARD"),
    ("CHEMBL1489", "AZACITIDINE"),
    ("CHEMBL1490", "TRIHEXYPHENIDYL"),
    ("CHEMBL1491", "AMLODIPINE"),
    ("CHEMBL1492", "DIPHENYLPYRALINE"),
    ("CHEMBL1493", "FLAVOXATE"),
    ("CHEMBL1494", "NORFLUOXETINE"),
    ("CHEMBL1495", "OXYPHENCYCLIMINE"),
    ("CHEMBL1496", "ROSUVASTATIN"),
    ("CHEMBL1497", "BETAMETHASONE VALERATE"),
    ("CHEMBL1498", "DESOXYCORTICOSTERONE"),
    ("CHEMBL1499", "CORTISONE"),
    ("CHEMBL1500", "DIHYDROMORPHINE"),
    ("CHEMBL1501", "FLUOCINONIDE"),
    ("CHEMBL1502", "PANTOPRAZOLE"),
    ("CHEMBL1503", "OMEPRAZOLE"),
    ("CHEMBL1504", "TRIAMCINOLONE ACETONIDE"),
    ("CHEMBL1505", "ALMOTRIPTAN"),
    ("CHEMBL1506", "CHLORAMPHENICOL PALMITATE"),
    ("CHEMBL1508", "ESCITALOPRAM"),
    ("CHEMBL1509", "DROSPIRENONE"),
    ("CHEMBL1510", "ELETRIPTAN"),
    ("CHEMBL1511", "ESTRADIOL VALERATE"),
    ("CHEMBL1512", "FLUNISOLIDE"),
    ("CHEMBL1513", "IRBESARTAN"),
    ("CHEMBL1514", "LEVOMETHADYL ACETATE"),
    ("CHEMBL1515", "METHIMAZOLE"),
    ("CHEMBL1516", "OLMESARTAN"),
    ("CHEMBL1517", "OXYTETRACYCLINE"),
    ("CHEMBL1518", "PROPYLTHIOURACIL"),
    ("CHEMBL1519", "TRANDOLAPRIL"),
    ("CHEMBL1520", "VARDENAFIL"),
    ("CHEMBL1521", "ZALEPLON"),
    ("CHEMBL1522", "ESZOPICLONE"),
    ("CHEMBL1523", "NORSANGUININE"),
    ("CHEMBL1524", "SANGUININE"),
    ("CHEMBL1525", "PERMETHRIN"),
    ("CHEMBL1528", "SODIUM FLUORIDE"),
    ("CHEMBL1529", "DIPHENIDOL HYDROCHLORIDE"),
    ("CHEMBL1531", "ETONOGESTREL"),
    ("CHEMBL1532", "QUINETHAZONE"),
    ("CHEMBL1533", "DESOGESTREL"),
    ("CHEMBL1534", "RIBOFLAVIN"),
    ("CHEMBL1535", "HYDROXYCHLOROQUINE"),
    ("CHEMBL1536", "ERGOCALCIFEROL"),
    ("CHEMBL1537", "AZLOCILLIN"),
    ("CHEMBL1538", "TENOFOVIR DISOPROXIL"),
    ("CHEMBL1539", "SULFADOXINE"),
    ("CHEMBL1540", "PENCICLOVIR"),
    ("CHEMBL1541", "CEFIXIME"),
    ("CHEMBL1542", "AZATHIOPRINE"),
    ("CHEMBL1543", "GLUTATHIONE"),
    ("CHEMBL1544", "LIOTHYRONINE"),
    ("CHEMBL1545", "TIZOXANIDE"),
    ("CHEMBL1546", "HYDROXYAMPHETAMINE"),
    ("CHEMBL1547", "THIAMINE ION"),
    ("CHEMBL1549", "HYDROCORTISONE CYPIONATE"),
    ("CHEMBL1550", "PHYTONADIONE"),
    ("CHEMBL1551", "URSODIOL"),
    ("CHEMBL1552", "GLYCOCHENODEOXYCHOLATE"),
    ("CHEMBL1554", "DACTINOMYCIN"),
    ("CHEMBL1555", "GALANTAMINE HYDROBROMIDE"),
    ("CHEMBL1556", "INOSINE"),
    ("CHEMBL1557", "DOPAMINE HYDROCHLORIDE"),
    ("CHEMBL1558", "PRAZOSIN HYDROCHLORIDE"),
    ("CHEMBL1559", "MICONAZOLE NITRATE"),
    ("CHEMBL1560", "CAPTOPRIL"),
    ("CHEMBL1561", "MIGLITOL"),
    ("CHEMBL1562", "HOMOVANILLIC ACID"),
    ("CHEMBL1563", "DAUNORUBICIN HYDROCHLORIDE"),
    ("CHEMBL1564", "DIPHENYLPYRALINE HYDROCHLORIDE"),
    ("CHEMBL1567", "SUNITINIB MALATE"),
    ("CHEMBL1568", "FLUDARABINE"),
    ("CHEMBL1569", "AMANTADINE HYDROCHLORIDE"),
    ("CHEMBL1570", "SULFOXONE"),
    ("CHEMBL1571", "TESTOLACTONE"),
    ("CHEMBL1572", "NETILMICIN"),
    ("CHEMBL1574", "PHENTERMINE"),
    ("CHEMBL1575", "ESTRAMUSTINE"),
    ("CHEMBL1576", "ETHINAMATE"),
    ("CHEMBL1577", "METHYCLOTHIAZIDE"),
    ("CHEMBL1578", "ANISOTROPINE METHYLBROMIDE"),
    ("CHEMBL1579", "PARAMETHASONE"),
    ("CHEMBL1580", "PENTOSTATIN"),
    ("CHEMBL1581", "PERINDOPRIL"),
    ("CHEMBL1582", "DROMOSTANOLONE"),
    ("CHEMBL1583", "BACAMPICILLIN"),
    ("CHEMBL1584", "PIPERACETAZINE"),
    ("CHEMBL1585", "PIPOBROMAN"),
    ("CHEMBL1586", "BECLOMETHASONE"),
    ("CHEMBL1587", "POLYTHIAZIDE"),
    ("CHEMBL1588", "THIAMINE"),
    ("CHEMBL1589", "ACETOHEXAMIDE"),
    ("CHEMBL1590", "PSEUDOEPHEDRINE"),
    ("CHEMBL1591", "DEMECLOCYCLINE"),
    ("CHEMBL1592", "QUINAPRIL"),
    ("CHEMBL1593", "ALDOPHOSPHAMIDE"),
    ("CHEMBL1594", "PANTOTHENIC ACID"),
    ("CHEMBL1595", "DIHYDROCODEINE"),
    ("CHEMBL1596", "CARBENICILLIN INDANYL"),
    ("CHEMBL1597", "DIMERCAPROL"),
    ("CHEMBL1599", "CEPHAPIRIN"),
    ("CHEMBL1600", "DESETHYLAMIODARONE"),
    ("CHEMBL1601", "CEFONICID"),
    ("CHEMBL1602", "STILBESTROL DISULFATE"),
    ("CHEMBL1604", "CEPHRADINE"),
    ("CHEMBL1605", "CEFTIBUTEN"),
    ("CHEMBL1607", "TOPOTECAN HYDROCHLORIDE"),
    ("CHEMBL1608", "DESMETHYLMIFEPRISTONE"),
    ("CHEMBL1609", "MANDELIC ACID"),
    ("CHEMBL1611", "PHENYTOIN SODIUM"),
    ("CHEMBL1614", "DESLANOSIDE"),
    ("CHEMBL1617", "RIFAXIMIN"),
    ("CHEMBL1618", "CEFAMANDOLE NAFATE"),
    ("CHEMBL1619", "CLADRIBINE"),
    ("CHEMBL1620", "DIPHENHYDRAMINE HYDROCHLORIDE"),
    ("CHEMBL1621", "PALIPERIDONE"),
    ("CHEMBL1622", "FOLIC ACID"),
    ("CHEMBL1623", "MECLIZINE"),
    ("CHEMBL1624", "LEVOTHYROXINE"),
    ("CHEMBL1625", "OXYBENZONE"),
    ("CHEMBL1626", "CLEMASTINE"),
    ("CHEMBL1631", "BIDESETHYL AMODIAQUINE"),
    ("CHEMBL1632", "CEPHALOTHIN SODIUM"),
    ("CHEMBL1633", "KETOTIFEN FUMARATE"),
    ("CHEMBL1637", "GEMCITABINE HYDROCHLORIDE"),
    ("CHEMBL1639", "ALISKIREN"),
    ("CHEMBL1640", "TRYPAN BLUE"),
    ("CHEMBL1641", "HYDROCORTISONE PHOSPHORIC ACID"),
    ("CHEMBL1642", "IMATINIB MESYLATE"),
    ("CHEMBL1643", "RIBAVIRIN"),
    ("CHEMBL1644", "CEFADROXIL"),
    ("CHEMBL1646", "INDOCYANINE GREEN"),
    ("CHEMBL1647", "ACETAMINOPHEN GLUCURONIDE"),
    ("CHEMBL1648", "ISRADIPINE"),
    ("CHEMBL1649", "DEMETHYL-CITALOPRAM"),
    ("CHEMBL1650", "CORTISONE ACETATE"),
    ("CHEMBL1652", "AMBENONIUM"),
    ("CHEMBL1653", "PHENIRAMINE MALEATE"),
    ("CHEMBL1654", "RISEDRONATE SODIUM"),
    ("CHEMBL1655", "TOREMIFENE"),
    ("CHEMBL1656", "BIDESETHYL CHLOROQUINE"),
    ("CHEMBL1657", "TAZAROTENE"),
    ("CHEMBL1658", "RETAPAMULIN"),
    ("CHEMBL1659", "CHLORPHENIRAMINE MALEATE"),
    ("CHEMBL1660", "RIFAPENTINE"),
    ("CHEMBL1661", "LACTITOL"),
    ("CHEMBL1663", "PERFLUTREN"),
    ("CHEMBL1664", "FOSAMPRENAVIR"),
    ("CHEMBL1665", "ALBENDAZOLE OXIDE"),
    ("CHEMBL1668", "RESCINNAMINE"),
    ("CHEMBL1670", "MITOTANE"),
    ("CHEMBL1671", "PROPRANOLOL HYDROCHLORIDE"),
    ("CHEMBL1672", "CEFPODOXIME"),
    ("CHEMBL1673", "ACYCLOVIR TRIPHOSPHATE"),
    ("CHEMBL1674", "TELBIVUDINE 5'TRIPHOSPHATE"),
    ("CHEMBL1675", "VITAMIN A PALMITATE"),
    ("CHEMBL1676", "FLUTICASONE FUROATE"),
    ("CHEMBL1677", "TACRINE HYDROCHLORIDE"),
    ("CHEMBL1678", "DONEPEZIL HYDROCHLORIDE"),
    ("CHEMBL1679", "LEUCOVORIN"),
    ("CHEMBL1680", "OCTREOTIDE"),
    ("CHEMBL1681", "IODOHIPPURATE"),
    ("CHEMBL1682", "SORBITOL"),
    ("CHEMBL1683", "HYDROCORTISONE BUTYRATE"),
    ("CHEMBL1684", "BENDROFLUMETHIAZIDE"),
    ("CHEMBL1685", "DEZOCINE"),
    ("CHEMBL1686", "ALPHA-KETOGLUTARIC ACID"),
    ("CHEMBL1689", "TOLAZOLINE HYDROCHLORIDE"),
    ("CHEMBL1690", "HYDROXYCHLOROQUINE SULFATE"),
    ("CHEMBL1691", "BETAXOLOL HYDROCHLORIDE"),
    ("CHEMBL1692", "IMIPRAMINE HYDROCHLORIDE"),
    ("CHEMBL1693", "DIETHYLPROPION HYDROCHLORIDE"),
    ("CHEMBL1694", "BENAZEPRIL HYDROCHLORIDE"),
    ("CHEMBL1695", "TIAGABINE HYDROCHLORIDE"),
    ("CHEMBL1696", "DESIPRAMINE HYDROCHLORIDE"),
    ("CHEMBL1697", "DILTIAZEM HYDROCHLORIDE"),
    ("CHEMBL1698", "BUPROPION HYDROCHLORIDE"),
    ("CHEMBL1699", "MEMANTINE HYDROCHLORIDE"),
    ("CHEMBL1700", "SOTALOL HYDROCHLORIDE"),
    ("CHEMBL1701", "MEPERIDINE HYDROCHLORIDE"),
    ("CHEMBL1702", "ATOMOXETINE HYDROCHLORIDE"),
    ("CHEMBL1703", "METFORMIN HYDROCHLORIDE"),
    ("CHEMBL1705", "CLONIDINE HYDROCHLORIDE"),
    ("CHEMBL1706", "NAPHAZOLINE HYDROCHLORIDE"),
    ("CHEMBL1707", "LOPERAMIDE HYDROCHLORIDE"),
    ("CHEMBL1709", "SERTRALINE HYDROCHLORIDE"),
    ("CHEMBL1711", "ISOPROTERENOL HYDROCHLORIDE"),
    ("CHEMBL1713", "CHLORPROMAZINE HYDROCHLORIDE"),
    ("CHEMBL1714", "KETAMINE HYDROCHLORIDE"),
    ("CHEMBL1715", "PIOGLITAZONE HYDROCHLORIDE"),
    ("CHEMBL1716", "CYPROHEPTADINE HYDROCHLORIDE"),
    ("CHEMBL1717", "TICLOPIDINE HYDROCHLORIDE"),
    ("CHEMBL1718", "NALOXONE HYDROCHLORIDE"),
    ("CHEMBL1719", "OLOPATADINE HYDROCHLORIDE"),
    ("CHEMBL1720", "PALONOSETRON HYDROCHLORIDE"),
    ("CHEMBL1722", "METHYLPHENIDATE HYDROCHLORIDE"),
    ("CHEMBL1723", "ALFUZOSIN HYDROCHLORIDE"),
    ("CHEMBL1724", "MEPENZOLATE BROMIDE"),
    ("CHEMBL1725", "IOPROMIDE"),
    ("CHEMBL1726", "NISOLDIPINE"),
    ("CHEMBL1727", "CEPHALEXIN ANHYDROUS"),
    ("CHEMBL1728", "LOMEFLOXACIN HYDROCHLORIDE"),
    ("CHEMBL1729", "CISAPRIDE"),
    ("CHEMBL1730", "CEFOTAXIME"),
    ("CHEMBL1731", "MEZLOCILLIN"),
    ("CHEMBL1732", "DIHYDROERGOTAMINE"),
    ("CHEMBL1733", "QUINAPRILAT"),
    ("CHEMBL1734", "SOLIFENACIN"),
    ("CHEMBL1735", "INDINAVIR SULFATE"),
    ("CHEMBL1736", "METRIZOIC ACID"),
    ("CHEMBL1737", "SILDENAFIL CITRATE"),
    ("CHEMBL1738", "DEXRAZOXANE"),
    ("CHEMBL1739", "METOCURINE IODIDE"),
    ("CHEMBL1740", "RACEPINEPHRINE"),
    ("CHEMBL1741", "CLARITHROMYCIN"),
    ("CHEMBL1743", "CEFDITOREN"),
    ("CHEMBL1745", "METHYLDIETHYL CARBAMODITHIOATE"),
    ("CHEMBL1746", "SODIUM PHENYLBUTYRATE"),
    ("CHEMBL1747", "TOBRAMYCIN"),
    ("CHEMBL1748", "NORCISAPRIDE"),
    ("CHEMBL1749", "EDETATE DISODIUM ANHYDROUS"),
    ("CHEMBL1750", "CLOFARABINE"),
    ("CHEMBL1751", "DIGOXIN"),
    ("CHEMBL1752", "DYPHYLLINE"),
    ("CHEMBL1753", "CLINDAMYCIN"),
    ("CHEMBL1754", "DOXAPRAM"),
    ("CHEMBL1755", "CONIVAPTAN"),
    ("CHEMBL1756", "ESTRAMUSTINE PHOSPHATE"),
    ("CHEMBL1757", "FOSFOMYCIN"),
    ("CHEMBL1760", "TERBUTALINE"),
    ("CHEMBL1761", "PROCYCLIDINE HYDROCHLORIDE"),
    ("CHEMBL1762", "TOCAINIDE"),
    ("CHEMBL1763", "HYDROFLUMETHIAZIDE"),
    ("CHEMBL1764", "LEVOMEPROMAZINE"),
    ("CHEMBL1766", "DESOXIMETASONE"),
    ("CHEMBL1768", "BETHANECHOL CHLORIDE"),
    ("CHEMBL1769", "PROPOXYCAINE HYDROCHLORIDE"),
    ("CHEMBL1770", "LEVAMISOLE HYDROCHLORIDE"),
    ("CHEMBL1771", "CLOPIDOGREL"),
    ("CHEMBL1773", "CAPECITABINE"),
]